### ISSUE TITLE
при смене пароля первое окошко не скрывает пароль

### ISSUE THREAD

**Issue by dpolevodin** [study-process/give-me-stand#4]

**Comment by dpolevodin** [comment]
исправлено в коммите https://github.com/dpolevodin/GiveMeStand/pull/1/commits/088052f5b00c44992f307e5fbbfb25ce2b683d91

**Comment by study-process** [comment]
исправлено
<img width="524" alt="image" src="https://user-images.githubusercontent.com/107348420/175814093-adff3d5c-d9a8-4ee4-9278-8307147fedb2.png">
