### ISSUE TITLE
Накинуть background [lowest]

### ISSUE THREAD

**Issue by TarasovDaniil** [study-process/give-me-stand#5]
<img width="1164" alt="Снимок экрана 2022-06-22 в 19 08 31" src="https://user-images.githubusercontent.com/68328794/175050181-720b62d3-0749-4122-aec7-0ffe87ea5db6.png">
Хедер сливается с основной частью. Можно подставить градиент / цвет.

**Comment by study-process** [comment]
Готово
<img width="1479" alt="image" src="https://user-images.githubusercontent.com/107348420/175250343-1478e8ad-4fc3-4abe-ac78-bdc912188373.png">
