### ISSUE TITLE
Настроить routing [low]

### ISSUE THREAD

**Issue by TarasovDaniil** [study-process/give-me-stand#6]
Не хватает роутинга. Когда переходишь в приложение открываются занятые стенды. Переходишь во все стенды - но путь не меняется. Может можно как-то поправить, чтобы была ссылка именно на "Все стенды" ))

**Comment by study-process** [comment]
<img width="1484" alt="Снимок экрана 2022-06-26 в 18 03 10" src="https://user-images.githubusercontent.com/107348420/175815527-14feffca-38ac-486a-9e06-60bcc4a15bcf.png">
исправлено добавлен роут для всех стендов: /team-stands
